on: push
name: ðŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Use Node.js 14
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - name: ðŸ”¨ Install dependencies
        run: |
          npm install

      - name: ðŸ”¨ Build project
        run: |
          npm build

      - name: List output files
        run: find build/ -print

      - name: ðŸ“‚ Sync files to production
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        if: github.ref == 'refs/heads/main'
        with:
          server: ftp.fahrenheit.sui-inter.net
          username: tnh
          password: $FTP_PASSWORD
          local-dir: build/
          server-dir: embeddables/

      - name: ðŸ“‚ Sync files to staging
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        if: github.ref == 'refs/heads/staging'
        with:
          server: ftp.fahrenheit.sui-inter.net
          username: tnh
          password: $FTP_PASSWORD
          local-dir: build/
          server-dir: staging/
